src/main/java/br/com/gleac/supers/AbstractController.java
package br.com.gleac.supers;

import br.com.gleac.anotacao.CRUD;
import br.com.gleac.converters.ConverterAutoComplete;
import br.com.gleac.entidade.comum.Loja;
import br.com.gleac.entidade.seguranca.Recurso;
import br.com.gleac.enums.OperacaoCondicaoSql;
import br.com.gleac.enums.TipoComponente;
import br.com.gleac.exception.ValidacaoException;
import br.com.gleac.negocio.ViewRepository;
import br.com.gleac.service.SistemaService;
import br.com.gleac.util.ExcelUtil;
import br.com.gleac.util.FacesUtil;
import br.com.gleac.util.Persistencia;
import br.com.gleac.util.Util;
import br.com.gleac.util.view.*;
import com.google.common.collect.Lists;
import com.ocpsoft.pretty.PrettyContext;
import org.primefaces.model.StreamedContent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.util.ObjectUtils;
import org.springframework.web.context.support.SpringBeanAutowiringSupport;

import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;

/**
 * Created by renatoromanini on 25/08/15.
 */
public abstract class AbstractController<T> {

    public static final Logger log = LoggerFactory.getLogger(AbstractController.class);

    private static final Integer MAXIMO_REGISTROS_TABELA = 10;
    private List lista;
    private ConverterAutoComplete converterAutoComplete;
    protected Class<T> classe;
    public T selecionado;
    private Long id;
    private View view;
    @Autowired
    private ViewRepository viewRepository;
    @Autowired
    private SistemaService sistemaService;

    public abstract AbstractRepository getRepository();


    public AbstractController() {
        injetarDependenciasSpring();
    }

    protected Logger getLogger() {
        return LoggerFactory.getLogger(this.getClass());
    }

    public void realizarValidacao() {
        Util.validarCampos((AbstractEntity) selecionado);
    }

    public AbstractController(Class<T> classe) {
        this.classe = classe;
        this.view = new View();
        injetarDependenciasSpring();
    }

    public final void injetarDependenciasSpring() {
        ServletContext servletContext = (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();
        SpringBeanAutowiringSupport.processInjectionBasedOnServletContext(this, servletContext);
    }

    public ConverterAutoComplete getConverterAutoComplete() {
        if (converterAutoComplete == null) {
            converterAutoComplete = new ConverterAutoComplete(classe, getRepository());
        }
        return converterAutoComplete;
    }

    public void novo() {

        try {

            if (selecionado == null) {
                this.selecionado = classe.newInstance();
            }
            recuperarLojaSessao();
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbstractController.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbstractController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void recuperarLojaSessao() {
        if (esteSelecionadoPossuiLoja()) {
            try {
                getFieldLoja().set(selecionado, sistemaService.getLojaCorrente());
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            }
        }
    }

    public Field getFieldLoja() {
        for (Field field : Persistencia.getAtributos(classe)) {
            field.setAccessible(true);
            if (field.getType().equals(Loja.class)) {
                return field;
            }
        }
        return null;
    }

    public Boolean esteSelecionadoPossuiLoja() {
        for (Field field : Persistencia.getAtributos(classe)) {
            field.setAccessible(true);
            if (field.getType().equals(Loja.class)) {
                return Boolean.TRUE;
            }
        }
        return Boolean.FALSE;
    }

    public void listar() {
        filtrar();
    }

    public void editar() {
        this.selecionado = (T) getRepository().recuperar(classe, id);


    }

    public void visualizar() {
        this.selecionado = (T) getRepository().recuperar(classe, id);
    }

    public void salvar() {
        try {
            if (Persistencia.getId(this.selecionado) == null) {
                getRepository().salvarNovo(this.selecionado);
            } else {
                getRepository().salvar(this.selecionado);
            }
            FacesUtil.addInfo("Operação realizada com sucesso!", "O " + this.selecionado.toString() + " foi <b> salvo </b> com sucesso!");
        } catch (RuntimeException ex) {
            if (ex instanceof ValidacaoException) {
                FacesUtil.printAllFacesMessages(((ValidacaoException) ex).getMensagens());
            } else {
                FacesUtil.addErrorPadrao(ex);
            }
            return;
        } catch (Exception ex) {
            FacesUtil.addErrorPadrao(ex);
            return;
        }

        navegarEmbora();

    }

    public void navegarEmbora() {
        FacesUtil.navegaEmbora(selecionado, getCaminhoPadrao());
    }

    public String getCaminhoPadrao() {
        return ((AbstractEntity) selecionado).getCaminhoPadrao();
    }

    public void excluir() {
        try {
            getRepository().excluir(selecionado);
            lista = null;
            FacesUtil.addInfo("Operação realizada com sucesso.", "Registro excluido com sucesso");
            navegarEmbora();
        } catch (RuntimeException ex) {
            FacesUtil.addError("Operação não permitida.", ex.getMessage());
        } catch (Exception ex) {
            FacesUtil.addErrorPadrao(ex);
        }
    }

    public String getCaminhoNovo() {
        return getClasseAsSuperEntidade().getCaminhoPadrao() + "novo/";
    }

    public List<SelectItem> getObjetosSelectItem() {
        List<SelectItem> toReturn = new ArrayList();
        try {

            if (selecionado == null) {
                this.selecionado = classe.newInstance();
            }
            AbstractEntity se = (AbstractEntity) this.selecionado;
            String todos = "TOD" + se.getArtigoDefinidoDaEntidade() + "S " + se.getArtigoDefinidoDaEntidade() + "S " + se.getNomePluralDaEntidade() + ".";
            toReturn.add(new SelectItem(null, todos.toUpperCase()));
            for (Object obj : getRepository().listar()) {
                toReturn.add(new SelectItem(obj, obj.toString()));
            }


        } catch (Exception e) {

        }
        return Util.ordenaSelectItem(toReturn);

    }

    public List<T> recuperarTodos() {
        return getRepository().listar();
    }


    public List<Field> getAtributosTabelaveis() {
        return Persistencia.getAtributosTabelaveis(classe);
    }

    public String getNomeCampo(Field field) {
        return Persistencia.getNomeCampo(field);
    }

    public String getValorCampo(Field field, Object objeto) {
        return Persistencia.getValorCampo(field, objeto);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public T getSelecionado() {
        return selecionado;
    }

    public void setSelecionado(T selecionado) {
        this.selecionado = selecionado;
    }

    public void filtrar() {
        View view = getView();
        view.setNomeRelatorio("Relatório de " + Persistencia.getNomeEntidade(classe));
        view.setColunas(Lists.newArrayList());
        String sql = Persistencia.adicionarColunas(view, "obj", classe);
        String sqlSelect = " select obj.id, " + sql.substring(0, sql.length() - 2) + "  from " + classe.getSimpleName() + " obj " +
            " where 1=1 ";

        for (Field field : Persistencia.getAtributosPesquisaveis(classe)) {
            criarParametroView(view, field);
        }

        montarParametroLoja(view);

        view.setSqlRecuperadorObjetos(sqlSelect);
        view.setSqlOrdenar(" order by obj.id desc");
        view.setSqlContadorObjetos(" select count(obj.id)  from " + classe.getSimpleName() + " obj where 1=1 ");

        view = viewRepository.recuperarObjetos(view);
        view.setTotalDeRegistrosExistentes(null);
    }

    public void montarParametroLoja(View view) {
        Loja loja = sistemaService.getLojaCorrente();
        Field field = getFieldLoja();
        if (esteSelecionadoPossuiLoja() && loja != null && field != null && !sistemaService.isLojaGestora()) {
            ParametroView parametroView = new ParametroView(Persistencia.getNomeCampo(field), getCondicao(field), loja.getId(), OperacaoCondicaoSql.IGUAL, null, field.getType());
            view.getParametros().add(parametroView);
        }
    }

    private String getCondicao(Field field) {
        return "obj." + (field.getType().isAnnotationPresent(Entity.class) ? field.getName() + "_id" : field.getName());
    }

    public View getView() {
        return view;
    }

    public void setView(View view) {
        this.view = view;
    }

    public String getArtigoEntidade() {
        AbstractEntity obj;
        String PADRAO_INDEFINIDO = "o/a";
        try {
            obj = getClasseAsSuperEntidade();
            return obj.getArtigoDefinidoDaEntidade();
        } catch (ClassCastException cce) {
            return PADRAO_INDEFINIDO;
        }
    }

    public AbstractEntity getClasseAsSuperEntidade() {
        try {
            AbstractEntity obj = (AbstractEntity) classe.newInstance();
            return obj;

src/main/webapp/resources/components/aguarde.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:fc="http://java.sun.com/jsf/composite/components"
      xmlns:cc="http://java.sun.com/jsf/composite">

<!-- INTERFACE -->
<cc:interface>
</cc:interface>

<!-- IMPLEMENTATION -->
<cc:implementation>
    <!-- Modal -->
    <div class="modal fade" id="aguarde" tabindex="-1" role="dialog" aria-labelledby="aguarde">
        <div claaguardess="modal-dialog" role="document">
            <fc:spinner/>
        </div>
    </div>
</cc:implementation>
</html>

src/main/webapp/resources/components/completar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://java.sun.com/jsf/composite"
      xmlns:p="http://primefaces.org/ui">

<!-- INTERFACE -->
<cc:interface>
    <cc:attribute name="title" required="true"/>
    <cc:attribute name="value" required="true"/>
    <cc:attribute name="controller" required="true" type="br.com.gleac.supers.AbstractController"/>
</cc:interface>

<!-- IMPLEMENTATION -->
<cc:implementation>
    <p:autoComplete id="obj" title="#{cc.attrs.title}"
                    value="#{cc.attrs.value}"
                    completeMethod="#{cc.attrs.controller.completarEstaEntidade}"
                    var="ob"
                    queryDelay="0"
                    effectDuration="0"
                    itemLabel="#{ob}"
                    itemValue="#{ob}"
                    size="50"
                    onkeyup="maiuscula(this.id)"
                    onfocus="this.select()"
                    onclick="this.select()"
                    maxResults="20"
                    converter="#{cc.attrs.controller.converterAutoComplete}"/>
</cc:implementation>
</html>

src/main/webapp/resources/components/form-head.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://java.sun.com/jsf/composite"
>

<!-- INTERFACE -->
<cc:interface>
    <cc:attribute name="controlador" required="true"
                  type="br.com.gleac.supers.AbstractController"/>

</cc:interface>

<!-- IMPLEMENTATION -->
<cc:implementation>
    #{cc.attrs.controlador.selecionado.id eq null ? 'Nov' + cc.attrs.controlador.artigoEntidade : 'Editar'} #{cc.attrs.controlador.nomeEntidade}
</cc:implementation>
</html>

src/main/webapp/resources/components/head.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://java.sun.com/jsf/composite"
>

<!-- INTERFACE -->
<cc:interface>
    <cc:attribute name="title" required="true"/>

</cc:interface>

<!-- IMPLEMENTATION -->
<cc:implementation>
        Pesquisa de #{cc.attrs.title}
</cc:implementation>
</html>

src/main/webapp/resources/components/imports.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:cc="http://java.sun.com/jsf/composite">

<!-- INTERFACE -->
<cc:interface>
</cc:interface>

<!-- IMPLEMENTATION -->
<cc:implementation>

    <!--&lt;!&ndash;calendar&ndash;&gt;-->
    <h:outputScript library="js" name="locales-primefaces.js"/>


    <h:outputStylesheet library="css" name="bootstrap.css"/>
    <h:outputStylesheet library="css" name="style.css"/>
    <h:outputStylesheet library="css" name="style_1.css"/>
    <h:outputStylesheet library="css" name="plugins/dataTables/datatables.min.css"/>
    <h:outputStylesheet library="css" name="animate.css"/>
    <h:outputStylesheet library="font-awesome" name="css/font-awesome.css"/>

    <!--Biblioteca 'jquery-ui-1.10.4.min.js' comentada para funcionamento correto do componente <p:fileUpload>-->
    <!--<h:outputScript library="js" name="jquery-2.1.1.js"/>-->
    <!--<h:outputScript library="js" name="bootstrap.min.js"/>
    <h:outputScript library="js" name="plugins/metisMenu/jquery.metisMenu.js"/>
    <h:outputScript library="js" name="plugins/slimscroll/jquery.slimscroll.js"/>
    &lt;!&ndash;Biblioteca 'jquery-ui-1.10.4.min.js' comentada para funcionamento correto do componente <p:calendar>&ndash;&gt;
    &lt;!&ndash;<h:outputScript library="js" name="jquery-ui-1.10.4.min.js"/>&ndash;&gt;
    <h:outputScript library="js" name="plugins/dataTables/datatables.min.js"/>
    <h:outputScript library="js" name="inspinia.js"/>
    <h:outputScript library="js" name="bootstrap.js"/>-->


    <script src="/resources/js/bootstrap.min.js"></script>
    <script src="/resources/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="/resources/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="/resources/js/plugins/dataTables/datatables.min.js"></script>

    <script src="/resources/js/inspinia.js"></script>


    <script src="/resources/js/function-sge.js"></script>
    <h:outputScript library="js" name="Chart.min.js"/>

</cc:implementation>
</html>

src/main/webapp/resources/components/item-menu.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://java.sun.com/jsf/composite">

<!-- INTERFACE -->
<cc:interface>
    <cc:attribute name="path" type="java.lang.String" default=""  required="true"/>
    <cc:attribute name="icone" type="java.lang.String" default="" required="false"/>
    <cc:attribute name="descricao" type="java.lang.String" default="" required="true"/>
    <cc:attribute name="controller" required="true" type="br.com.gleac.controlador.HomeControlador"/>
</cc:interface>

<!-- IMPLEMENTATION -->
<cc:implementation>

    <li><a href="#{request.contextPath} #{cc.attrs.controller.getUrlMapped(cc.attrs.path)}">
        <!--<c:if test="#{empty cc.attrs.icone}">-->
            <!--<i class=""/>-->
        <!--</c:if>-->
        #{cc.attrs.descricao}</a>
    </li>

</cc:implementation>
</html>

src/main/webapp/resources/components/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://java.sun.com/jsf/composite"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:fc="http://java.sun.com/jsf/composite/components"
>

<!-- INTERFACE -->
<cc:interface>
</cc:interface>

<!-- IMPLEMENTATION -->
<cc:implementation>

    <nav class="navbar-default navbar-static-side animated fadeInLeft" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element">
                        <div style="text-align: center">
                            <c:if test="#{homeControlador.usuario.arquivo eq null}">
                                <img
                                    src="#{facesContext.externalContext.requestContextPath}/resources/images/no_user.png"
                                    alt="image" class="img-circle" style="text-align: center!important;"/>
                            </c:if>
                            <c:if test="#{homeControlador.usuario.arquivo ne null}">
                                <img
                                    src="#{facesContext.externalContext.requestContextPath}/arquivo?id=#{homeControlador.usuario.arquivo.id}"
                                    alt="image" class="img-circle " style="text-align: center!important;"/>
                            </c:if>

                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong
                                class="font-bold">${homeControlador.getUsuario()}</strong>
                             </span> <span class="text-muted text-xs block">Configurações<b
                                class="caret"></b></span> </span> </a>
                        </div>

                        <ul class="dropdown-menu animated fadeInRight m-t-xs">
                            <li><a href="profile.html">Profile</a></li>
                            <li><a href="contacts.html">Contacts</a></li>
                            <li><a href="mailbox.html">Mailbox</a></li>
                            <li class="divider"></li>
                            <li><a href="login.html">Logout</a></li>
                        </ul>
                    </div>
                    <div class="logo-element">
                        Gleac
                    </div>
                </li>
                <li class="active"><a href="#{request.contextPath}/admin/home" onclick="aguarde()"><i
                    class="fa fa-home"></i>
                    <span>Home</span></a>
                </li>
                <!--menu-->
                <ui:repeat value="#{homeControlador.moduloSistemaPorUsuario}" var="modulo" >
                    <li>
                        <a>
                        <i class="#{modulo.icone}"></i>
                        <span class="nav-label">#{modulo.descricao}</span>
                        <span class="fa arrow"></span>
                        </a>


                        <!--menu item -->
                        <ul class="nav nav-second-level">

                        <ui:repeat value="#{modulo.recursos}" var="recurso" >
                            <fc:item-menu controller="#{homeControlador}"
                                          descricao="#{recurso.recursoSistema.descricao}"
                                          path="#{recurso.recursoSistema.path}"/>
                        </ui:repeat>
                        </ul>
                    </li>
                </ui:repeat>
            </ul>


        </div>
    </nav>
</cc:implementation>
</html>

src/main/webapp/resources/components/rodape.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://java.sun.com/jsf/composite">

<!-- INTERFACE -->
<cc:interface>
</cc:interface>

<!-- IMPLEMENTATION -->
<cc:implementation>

    <!-- footer content -->
    <footer class="footer modal-footer ajustarfooter"  >
        <div class="pull-right">
            <a href="#"> Grande Loja Maçonica do Estado do Acre </a>
        </div>
        <div class="clearfix"></div>
    </footer>
</cc:implementation>
</html>

src/main/webapp/resources/components/rodapePadrao.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://java.sun.com/jsf/composite"
      xmlns:p="http://primefaces.org/ui"
>

<!-- INTERFACE -->
<cc:interface>
    <cc:attribute name="controlador" required="true"/>
    <cc:attribute name="navegaEmboraVoltar" required="false" method-signature="void execute()" default="null"/>
</cc:interface>

<!-- IMPLEMENTATION -->
<cc:implementation>
    <div class="row">
        <p:commandButton value="Salvar"
                         onclick="abrirStatusDialog() "
                         oncomplete="fechaStatusDialog()"
                         icon="fa  fa-save"
                         ajax="false"
                         styleClass="button-search m-t m-l-xs"
                         rendered="#{cc.attrs.controlador.mostrarBotaoSalvar(request)}"
                         style="outline: none"
                         actionListener="#{cc.attrs.controlador.salvar()}"
        />

        <p:commandButton value="Voltar"
                         onclick="abrirStatusDialog() "
                         oncomplete="fechaStatusDialog()"
                         styleClass="button-clean m-t m-l-xs"
                         icon="fa fa-close"
                         immediate="true"
                         style="outline: none"
                         ajax="false"
                         action="#{cc.attrs.controlador.navegarEmbora()}"
        />

    </div>
</cc:implementation>
</html>

src/main/webapp/resources/components/rodapePadraoVisualizar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:cc="http://java.sun.com/jsf/composite"
      xmlns:p="http://primefaces.org/ui"
>

    <!-- INTERFACE -->
    <cc:interface>
        <cc:attribute name="controlador" required="true"/>
        <cc:attribute name="mostrarEditar" default="true" type="java.lang.Boolean" required="false" />
        <cc:attribute name="mostrarImprimir" default="false" type="java.lang.Boolean" required="false" />
        <cc:attribute name="actionImprimir"  method-signature="void execute()" required="false" />
    </cc:interface>

    <!-- IMPLEMENTATION -->
    <cc:implementation>

        <p:button value="Editar"
                         title="Clique para editar este registro."
                         icon="fa fa-edit"
                         onclick="abrirStatusDialog() "
                         oncomplete="fechaStatusDialog()"
                         rendered="#{cc.attrs.mostrarEditar}"
                         styleClass="button-search m-t m-l-xs"
                         href="#{cc.attrs.controlador.selecionado.caminhoPadrao}editar/#{cc.attrs.controlador.selecionado.id}/"/>

        <p:commandButton value="Excluir"
                         title="Clique para remover este registro."
                         icon="fa fa-trash"
                         styleClass="button-excluir m-t m-l-xs"
                         actionListener="#{cc.attrs.controlador.excluir()}"
                         rendered="#{cc.attrs.controlador.mostrarBotaoExcluir(request)}"
                         onstart="abrirStatusDialog() "
                         oncomplete="fechaStatusDialog()"
                         onclick="if (!confirm('Deseja excluir este registro?'))
                                     return false;"/>

        <p:commandButton value="Voltar"
                         styleClass="button-clean m-t m-l-xs"
                         icon="fa fa-close"
                         immediate="true"
                         onclick="abrirStatusDialog() "
                         oncomplete="fechaStatusDialog()"
                         actionListener="#{cc.attrs.controlador.navegarEmbora()}"/>


        <h:commandLink target="_blank"
                       rendered="#{cc.attrs.mostrarImprimir}"
                       actionListener="#{cc.attrs.actionImprimir}"
                       title="Clique para imprimir o relatório."
        >
            <p:commandButton value="Imprimir"
                             ajax="false"
                             update="@form"
                             icon="fa fa-print"
                             styleClass="button-back m-t m-l-xs"
                             title="Clique para imprimir o relatório.">

            </p:commandButton>
        </h:commandLink>


    </cc:implementation>
</html>

src/main/webapp/resources/components/spinner.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://java.sun.com/jsf/composite">

<!-- INTERFACE -->
<cc:interface>
</cc:interface>

<!-- IMPLEMENTATION -->
<cc:implementation>

    <div class="spiner-example">
        <div class="sk-spinner sk-spinner-fading-circle">
            <div class="sk-circle1 sk-circle"></div>
            <div class="sk-circle2 sk-circle"></div>
            <div class="sk-circle3 sk-circle"></div>
            <div class="sk-circle4 sk-circle"></div>
            <div class="sk-circle5 sk-circle"></div>
            <div class="sk-circle6 sk-circle"></div>
            <div class="sk-circle7 sk-circle"></div>
            <div class="sk-circle8 sk-circle"></div>
            <div class="sk-circle9 sk-circle"></div>
            <div class="sk-circle10 sk-circle"></div>
            <div class="sk-circle11 sk-circle"></div>
            <div class="sk-circle12 sk-circle"></div>
        </div>
    </div>
</cc:implementation>
</html>

src/main/webapp/resources/components/titulo-panel.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://java.sun.com/jsf/composite"
>

<!-- INTERFACE -->
<cc:interface>
    <cc:attribute name="title" required="true"/>

</cc:interface>

<!-- IMPLEMENTATION -->
<cc:implementation>
    <div class="panel-title panel-primary panel-heading">
        <h3>#{cc.attrs.title}</h3>
    </div>
</cc:implementation>
</html>