src/main/java/br/com/gleac/supers/AbstractReportController.java
package br.com.gleac.supers;

import br.com.gleac.entidade.comum.ConfiguracaoCabecalho;
import br.com.gleac.entidade.comum.Loja;
import br.com.gleac.exception.ValidacaoException;
import br.com.gleac.negocio.ConfiguracaoCabecalhoRepository;
import br.com.gleac.negocio.LojaRepository;
import br.com.gleac.service.SistemaService;
import br.com.gleac.util.FacesUtil;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.context.support.SpringBeanAutowiringSupport;

import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import java.util.HashMap;

/**
 * Created by renatoromanini on 25/08/15.
 */
public abstract class AbstractReportController {


    @Autowired
    private AbstractReport abstractReport;
    @Autowired
    private ConfiguracaoCabecalhoRepository configuracaoCabecalhoRepository;
    private Loja lojaCorrente;
    @Autowired
    protected SistemaService sistemaService;
    @Autowired
    private LojaRepository lojaRepository;

    public AbstractReportController() {
        injetarDependenciasSpring();
    }

    protected Logger getLogger() {
        return LoggerFactory.getLogger(this.getClass());
    }

    public final void injetarDependenciasSpring() {
        ServletContext servletContext = (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();
        SpringBeanAutowiringSupport.processInjectionBasedOnServletContext(this, servletContext);
    }

    public void gerarRelatorio() {
        try {
            abstractReport.gerarRelatorio(getNomeJasper(), getParametros());
        } catch (ValidacaoException ex) {
            FacesUtil.printAllFacesMessages(ex.getMensagens());
        } catch (Exception e) {
            e.printStackTrace();
            FacesUtil.addError("Problema ao gerar relatório!", e.getMessage());
        }
    }

    public void gerarRelatorio(HashMap parametros) {
        try {
            abstractReport.gerarRelatorio(getNomeJasper(), parametros);
        } catch (ValidacaoException ex) {
            ex.printStackTrace();
            FacesUtil.printAllFacesMessages(ex.getMensagens());
        } catch (Exception e) {
            e.printStackTrace();
            FacesUtil.addError("Problema ao gerar relatório!", e.getMessage());
        }
    }

    public void gerarRelatorioComDadosEmCollection(JRBeanCollectionDataSource jrbc) {
        try {
            abstractReport.gerarRelatorioComDadosEmCollectionAlterandoNomeArquivo(getNomePDF(), getNomeJasper(), getParametros(), jrbc);
        } catch (ValidacaoException ex) {
            FacesUtil.printAllFacesMessages(ex.getMensagens());
        } catch (Exception e) {
            FacesUtil.addError("Problema ao gerar relatório!", e.getMessage());
        }
    }

    public ConfiguracaoCabecalho getConfiguracaoCabecalho() {
        ConfiguracaoCabecalho configuracao = configuracaoCabecalhoRepository.buscarConfiguracaoCabecalho();
        try {
            return configuracao;
        } catch (Exception ex) {
            FacesUtil.addOperacaoNaoRealizada("Configuração não encontrada!");
            return null;
        }
    }

    public Loja getLojaCorrente() {
        if (lojaCorrente == null) {
            lojaCorrente = sistemaService.getLojaCorrente();
        }
        return lojaCorrente;
    }

    public boolean isLojaGestora() {
        return lojaRepository.buscarLojaGestora().equals(getLojaCorrente());
    }

    public String getCaminho() {
        return abstractReport.getCaminho();
    }

    public abstract String getNomeJasper();

    public abstract String getNomePDF();

    public abstract HashMap getParametros();

    public AbstractReport getAbstractReport() {
        return abstractReport;
    }
}

src/main/webapp/admin/relatorios/macon-end-tel-email.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
>
<ui:composition template="../../resources/template/template.xhtml">
    <ui:define name="head"> <i class="fa fa-eye fa-1x"></i>
        Relatório de Maçons - Endereço, Telefone e E-mail
    </ui:define>
    <ui:define name="body">
        <h:form id="Formulario">
            <h:panelGrid columns="2">
                <h:outputLabel value="Loja: "
                               rendered="#{relatorioMaconControlador.lojaGestora}"/>
                <p:autoComplete value="#{relatorioMaconEndTelEmailControlador.loja}"
                                rendered="#{relatorioMaconControlador.lojaGestora}"
                                completeMethod="#{relatorioMaconEndTelEmailControlador.completarLoja}"
                                converter="#{relatorioMaconEndTelEmailControlador.converterLoja}"
                                var="l"
                                size="70"
                                maxResults="10"
                                itemLabel="#{l.toString()}"
                                itemValue="#{l}">
                </p:autoComplete>

                <h:outputLabel value="Grau: "/>
                <h:selectOneMenu value="#{relatorioMaconEndTelEmailControlador.grau}">
                    <f:selectItems value="#{relatorioMaconEndTelEmailControlador.getGraus()}"/>
                </h:selectOneMenu>

                <h:outputLabel value="Situação: "/>
                <h:selectOneMenu value="#{relatorioMaconEndTelEmailControlador.situacao}">
                    <f:selectItems value="#{relatorioMaconEndTelEmailControlador.getSituacoes()}"/>
                </h:selectOneMenu>
            </h:panelGrid>

            <h:commandLink actionListener="#{relatorioMaconEndTelEmailControlador.gerarRelatorio}"
                           target="_blank"
                           id="btGerar">
                <p:commandButton value="Gerar"
                                 icon="fa fa-print"
                                 ajax="false"
                                 style="width: 120px; height: 20px; min-height: 40px; margin-top: 10px;"
                                 styleClass="btn btn-default m-t mrg-lef05"
                                 id="btGerarRelatorio"/>
            </h:commandLink>

            <p:commandButton value="Gerar Excel"
                             icon="fa fa-file-excel-o"
                             actionListener="#{relatorioMaconEndTelEmailControlador.gerarRelatorioExcel}"
                             style="width: 150px; height: 20px; min-height: 40px; margin-top: 10px;"
                             styleClass="btn button-default m-t m-l-xs mrg-lef05"
                             title="Clique para fazer o download do arquivo gerado em excel."/>

            <p:commandButton value="Limpar"
                             icon="fa fa-refresh"
                             ajax="false"
                             update=":formulario"
                             process="@this"
                             actionListener="#{relatorioMaconEndTelEmailControlador.limparCampos}"
                             style="width: 120px; height: 20px; min-height: 40px; margin-top: 10px;"
                             styleClass="btn button-clean m-t m-l-xs"/>

            <p:poll interval="1"
                    widgetVar="poll"
                    update=":Formulario :formBarra"
                    listener="#{relatorioMaconEndTelEmailControlador.verificarTerminoProcesso()}"
                    autoStart="false"/>
        </h:form>

        <div class="modal fade" id="imprimir" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             style="z-index: 10000!important;">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Dados Gerados com Sucesso</h4>
                    </div>
                    <div class="modal-body">
                        <h:form id="formBarra">
                            <div class="alert alert-success">
                                <h4>Operação realizada com sucesso!</h4>
                                O Relatório de Maçons - Endereço, Telefone e E-mail está pronto para download.
                            </div>
                            <br/>
                            <h:panelGrid columns="2" style="width: 100%; text-align: center">
                                <p:commandButton value="Download"
                                                 process="@this"
                                                 ajax="false"
                                                 icon="fa fa-file-excel-o"
                                                 styleClass="mrig05 operacao"
                                                 title="Clique para fazer o download do arquivo gerado em excel.">
                                    <p:fileDownload value="#{relatorioMaconEndTelEmailControlador.fileDownload()}"/>
                                </p:commandButton>
                                <p:commandButton value="Fechar"
                                                 onclick="imprimir.hide();aguarde.hide();"
                                                 icon="ui-icon-close"
                                                 styleClass="operacao"
                                />
                            </h:panelGrid>
                        </h:form>
                    </div>
                    <div class="modal-footer">

                    </div>
                </div>
            </div>
        </div>
    </ui:define>
</ui:composition>
</html>

src/main/webapp/admin/relatorios/macon-grau.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
>
<ui:composition template="../../resources/template/template.xhtml">
    <ui:define name="head"> <i class="fa fa-eye fa-1x"></i>
        Relatório de Maçons - Grau Maçônico
    </ui:define>
    <ui:define name="body">
        <h:form id="Formulario">
            <h:panelGrid columns="2">
                <h:outputLabel value="Loja: "
                               rendered="#{relatorioMaconControlador.lojaGestora}"/>
                <p:autoComplete value="#{relatorioMaconPorGrauControlador.loja}"
                                rendered="#{relatorioMaconControlador.lojaGestora}"
                                completeMethod="#{relatorioMaconPorGrauControlador.completarLoja}"
                                converter="#{relatorioMaconPorGrauControlador.converterLoja}"
                                var="l"
                                size="70"
                                maxResults="10"
                                itemLabel="#{l.toString()}"
                                itemValue="#{l}">
                </p:autoComplete>

                <h:outputLabel value="Situação: "/>
                <h:selectOneMenu value="#{relatorioMaconPorGrauControlador.situacao}">
                    <f:selectItems value="#{relatorioMaconPorGrauControlador.getSituacoes()}"/>
                </h:selectOneMenu>

                <p:outputLabel for="dataReferencia" value="Data de Referência:"/>
                <p:calendar id="dataReferencia" value="#{relatorioMaconPorGrauControlador.dataReferencia}"
                            title="Digite uma Data de Referência"
                            locale="pt"
                            autocomplete="off" pattern="dd/MM/yyyy" size="10" maxlength="10"
                            navigator="true"
                            showButtonPanel="true"
                            onkeyup="mascara(this, mdata)"/>
            </h:panelGrid>

            <h:commandLink actionListener="#{relatorioMaconPorGrauControlador.gerarRelatorio}"
                           target="_blank"
                           id="btGerar">
                <p:commandButton value="Gerar"
                                 icon="fa fa-print"
                                 ajax="false"
                                 style="width: 120px; height: 20px; min-height: 40px; margin-top: 10px;"
                                 styleClass="btn btn-default m-t mrg-lef05"
                                 id="btGerarRelatorio"/>
            </h:commandLink>

            <p:commandButton value="Gerar Excel"
                             icon="fa fa-file-excel-o"
                             actionListener="#{relatorioMaconPorGrauControlador.gerarRelatorioExcel}"
                             style="width: 150px; height: 20px; min-height: 40px; margin-top: 10px;"
                             styleClass="btn button-default m-t m-l-xs mrg-lef05"
                             title="Clique para fazer o download do arquivo gerado em excel."/>

            <p:commandButton value="Limpar"
                             icon="fa fa-refresh"
                             ajax="false"
                             update=":formulario"
                             process="@this"
                             actionListener="#{relatorioMaconPorGrauControlador.limparCampos}"
                             style="width: 120px; height: 20px; min-height: 40px; margin-top: 10px;"
                             styleClass="btn button-clean m-t m-l-xs"/>

            <p:poll interval="1"
                    widgetVar="poll"
                    update=":Formulario :formBarra"
                    listener="#{relatorioMaconPorGrauControlador.verificarTerminoProcesso()}"
                    autoStart="false"/>
        </h:form>

        <div class="modal fade" id="imprimir" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             style="z-index: 10000!important;">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Dados Gerados com Sucesso</h4>
                    </div>
                    <div class="modal-body">
                        <h:form id="formBarra">
                            <div class="alert alert-success">
                                <h4>Operação realizada com sucesso!</h4>
                                O Relatório de Maçons - Grau Maçônico está pronto para download.
                            </div>
                            <br/>
                            <h:panelGrid columns="2" style="width: 100%; text-align: center">
                                <p:commandButton value="Download"
                                                 process="@this"
                                                 ajax="false"
                                                 icon="fa fa-file-excel-o"
                                                 styleClass="mrig05 operacao"
                                                 title="Clique para fazer o download do arquivo gerado em excel.">
                                    <p:fileDownload value="#{relatorioMaconPorGrauControlador.fileDownload()}"/>
                                </p:commandButton>
                                <p:commandButton value="Fechar"
                                                 onclick="imprimir.hide();aguarde.hide();"
                                                 icon="ui-icon-close"
                                                 styleClass="operacao"
                                />
                            </h:panelGrid>
                        </h:form>
                    </div>
                    <div class="modal-footer">

                    </div>
                </div>
            </div>
        </div>
    </ui:define>
</ui:composition>
</html>

src/main/webapp/admin/relatorios/macon-nascimento.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
>
<ui:composition template="../../resources/template/template.xhtml">
    <ui:define name="head"> <i class="fa fa-eye fa-1x"></i>
        Relatório de Maçons - Data de Nascimento
    </ui:define>
    <ui:define name="body">
        <h:form id="Formulario">
            <h:panelGrid columns="2">

                <h:outputLabel value="Mês / Ano:"/>
                <h:panelGrid columns="3"
                             cellpadding="0"
                             cellspacing="0">
                    <h:selectOneMenu value="#{relatorioMaconDataNascimentoControlador.mes}">
                        <f:selectItems value="#{relatorioMaconDataNascimentoControlador.getMeses()}"/>
                    </h:selectOneMenu>

                    <h:outputLabel value="/" styleClass="mlef05 mrig05"/>
                    <p:inputMask id="ano"
                                 mask="9999" size="4"
                                 value="#{relatorioMaconDataNascimentoControlador.ano}"/>
                </h:panelGrid>

                <h:outputLabel value="Loja: "
                               rendered="#{relatorioMaconControlador.lojaGestora}"/>
                <p:autoComplete value="#{relatorioMaconDataNascimentoControlador.loja}"
                                rendered="#{relatorioMaconControlador.lojaGestora}"
                                completeMethod="#{relatorioMaconDataNascimentoControlador.completarLoja}"
                                converter="#{relatorioMaconDataNascimentoControlador.converterLoja}"
                                var="l"
                                size="70"
                                maxResults="10"
                                itemLabel="#{l.toString()}"
                                itemValue="#{l}">
                </p:autoComplete>

                <h:outputLabel value="Grau: "/>
                <h:selectOneMenu value="#{relatorioMaconDataNascimentoControlador.grau}">
                    <f:selectItems value="#{relatorioMaconDataNascimentoControlador.getGraus()}"/>
                </h:selectOneMenu>

                <h:outputLabel value="Situação: "/>
                <h:selectOneMenu value="#{relatorioMaconDataNascimentoControlador.situacao}">
                    <f:selectItems value="#{relatorioMaconDataNascimentoControlador.getSituacoes()}"/>
                </h:selectOneMenu>
            </h:panelGrid>

            <h:commandLink actionListener="#{relatorioMaconDataNascimentoControlador.gerarRelatorio}"
                           target="_blank"
                           id="btGerar">
                <p:commandButton value="Gerar PDF"
                                 icon="fa fa-file-pdf-o"
                                 ajax="false"
                                 style="width: 150px; height: 20px; min-height: 40px; margin-top: 10px;"
                                 styleClass="btn button-default m-t m-l-xs mrg-lef05"
                                 id="btGerarRelatorio"/>
            </h:commandLink>

            <p:commandButton value="Gerar Excel"
                             icon="fa fa-file-excel-o"
                             actionListener="#{relatorioMaconDataNascimentoControlador.gerarRelatorioExcel}"
                             style="width: 150px; height: 20px; min-height: 40px; margin-top: 10px;"
                             styleClass="btn button-default m-t m-l-xs mrg-lef05"
                             title="Clique para fazer o download do arquivo gerado em excel.">
            </p:commandButton>

            <p:commandButton value="Limpar"
                             icon="fa fa-refresh"
                             ajax="false"
                             update=":formulario"
                             process="@this"
                             actionListener="#{relatorioMaconDataNascimentoControlador.limparCampos}"
                             style="width: 120px; height: 20px; min-height: 40px; margin-top: 10px;"
                             styleClass="btn button-clean m-t m-l-xs"/>

            <p:poll interval="1"
                    widgetVar="poll"
                    update=":Formulario :formBarra"
                    listener="#{relatorioMaconDataNascimentoControlador.verificarTerminoProcesso()}"
                    autoStart="false"/>
        </h:form>

        <div class="modal fade" id="imprimir" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             style="z-index: 10000!important;">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Dados Gerados com Sucesso</h4>
                    </div>
                    <div class="modal-body">
                        <h:form id="formBarra">
                            <div class="alert alert-success">
                                <h4>Operação realizada com sucesso!</h4>
                                O Relatório de Maçons por Data de Nascimento está pronto para download.
                            </div>
                            <br/>
                            <h:panelGrid columns="2" style="width: 100%; text-align: center">
                                <p:commandButton value="Download"
                                                 process="@this"
                                                 ajax="false"
                                                 icon="fa fa-file-excel-o"
                                                 styleClass="mrig05 operacao"
                                                 title="Clique para fazer o download do arquivo gerado em excel.">
                                    <p:fileDownload value="#{relatorioMaconDataNascimentoControlador.fileDownload()}"/>
                                </p:commandButton>
                                <p:commandButton value="Fechar"
                                                 onclick="imprimir.hide();aguarde.hide();"
                                                 icon="ui-icon-close"
                                                 styleClass="operacao"
                                />
                            </h:panelGrid>
                        </h:form>
                    </div>
                    <div class="modal-footer">

                    </div>
                </div>
            </div>
        </div>
    </ui:define>
</ui:composition>
</html>

src/main/webapp/admin/relatorios/macon-profissao.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
>
<ui:composition template="../../resources/template/template.xhtml">
    <ui:define name="head"> <i class="fa fa-eye fa-1x"></i>
        Relatório de Maçons - Profissão
    </ui:define>
    <ui:define name="body">
        <h:form id="Formulario">
            <h:panelGrid columns="2">
                <h:outputLabel value="Profissão: "/>
                <p:autoComplete value="#{relatorioMaconProfissaoControlador.profissao}"
                                completeMethod="#{relatorioMaconProfissaoControlador.completarProfissao}"
                                converter="#{relatorioMaconProfissaoControlador.converterProfissao}"
                                var="p"
                                size="70"
                                maxResults="10"
                                itemLabel="#{p.toString()}"
                                itemValue="#{p}">
                </p:autoComplete>

                <h:outputLabel value="Loja: "
                               rendered="#{relatorioMaconControlador.lojaGestora}"/>
                <p:autoComplete value="#{relatorioMaconProfissaoControlador.loja}"
                                rendered="#{relatorioMaconControlador.lojaGestora}"
                                completeMethod="#{relatorioMaconProfissaoControlador.completarLoja}"
                                converter="#{relatorioMaconProfissaoControlador.converterLoja}"
                                var="l"
                                size="70"
                                maxResults="10"
                                itemLabel="#{l.toString()}"
                                itemValue="#{l}">
                </p:autoComplete>

                <h:outputLabel value="Grau: "/>
                <h:selectOneMenu value="#{relatorioMaconProfissaoControlador.grau}">
                    <f:selectItems value="#{relatorioMaconProfissaoControlador.getGraus()}"/>
                </h:selectOneMenu>

                <h:outputLabel value="Situação: "/>
                <h:selectOneMenu value="#{relatorioMaconProfissaoControlador.situacao}">
                    <f:selectItems value="#{relatorioMaconProfissaoControlador.getSituacoes()}"/>
                </h:selectOneMenu>
            </h:panelGrid>

            <h:commandLink actionListener="#{relatorioMaconProfissaoControlador.gerarRelatorio}"
                           target="_blank"
                           id="btGerar">
                <p:commandButton value="Gerar"
                                 icon="fa fa-print"
                                 ajax="false"
                                 style="width: 120px; height: 20px; min-height: 40px; margin-top: 10px;"
                                 styleClass="btn btn-default m-t mrg-lef05"
                                 id="btGerarRelatorio"/>
            </h:commandLink>

            <p:commandButton value="Gerar Excel"
                             icon="fa fa-file-excel-o"
                             actionListener="#{relatorioMaconProfissaoControlador.gerarRelatorioExcel}"
                             style="width: 150px; height: 20px; min-height: 40px; margin-top: 10px;"
                             styleClass="btn button-default m-t m-l-xs mrg-lef05"
                             title="Clique para fazer o download do arquivo gerado em excel."/>

            <p:commandButton value="Limpar"
                             icon="fa fa-refresh"
                             ajax="false"
                             update=":formulario"
                             process="@this"
                             actionListener="#{relatorioMaconProfissaoControlador.limparCampos}"
                             style="width: 120px; height: 20px; min-height: 40px; margin-top: 10px;"
                             styleClass="btn button-clean m-t m-l-xs"/>

            <p:poll interval="1"
                    widgetVar="poll"
                    update=":Formulario :formBarra"
                    listener="#{relatorioMaconProfissaoControlador.verificarTerminoProcesso()}"
                    autoStart="false"/>
        </h:form>

        <div class="modal fade" id="imprimir" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             style="z-index: 10000!important;">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Dados Gerados com Sucesso</h4>
                    </div>
                    <div class="modal-body">
                        <h:form id="formBarra">
                            <div class="alert alert-success">
                                <h4>Operação realizada com sucesso!</h4>
                                O Relatório de Maçons - Profissão está pronto para download.
                            </div>
                            <br/>
                            <h:panelGrid columns="2" style="width: 100%; text-align: center">
                                <p:commandButton value="Download"
                                                 process="@this"
                                                 ajax="false"
                                                 icon="fa fa-file-excel-o"
                                                 styleClass="mrig05 operacao"
                                                 title="Clique para fazer o download do arquivo gerado em excel.">
                                    <p:fileDownload value="#{relatorioMaconProfissaoControlador.fileDownload()}"/>
                                </p:commandButton>
                                <p:commandButton value="Fechar"
                                                 onclick="imprimir.hide();aguarde.hide();"
                                                 icon="ui-icon-close"
                                                 styleClass="operacao"
                                />
                            </h:panelGrid>
                        </h:form>
                    </div>
                    <div class="modal-footer">

                    </div>
                </div>
            </div>
        </div>
    </ui:define>
</ui:composition>
</html>